# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'WAKEPARKBY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  # Pods for WAKEPARKBY

end
